- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: httpd3
      app.kubernetes.io/component: httpd3
      app.kubernetes.io/instance: httpd3
    name: httpd3
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: httpd3:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: https://github.com/jha-deepak9981/php-sample.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: httpd:2.4
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: J3YI5bITbdv6xI3fCjxR
      type: GitHub
    - generic:
        secret: 2M4LThktvmv4-_Bt05QC
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
